// SPDX-FileCopyrightText: 2026 Ryx Interactive
// SPDX-License-Identifier: GPL-3.0-only

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace RyxInteractive.ProjectAuditorRules.Tests;

public sealed class CodeSizeAnalyzerTests
{
    [Fact]
    public void Type_at_300_sloc_is_allowed_but_301_is_reported()
    {
        using var host = new AnalyzerTestHost();

        var allowed = BuildClass(297);
        var overLimit = BuildClass(298);

        Assert.DoesNotContain(host.Analyze(allowed), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
        Assert.Contains(host.Analyze(overLimit), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Member_at_30_sloc_is_allowed_but_31_is_reported()
    {
        using var host = new AnalyzerTestHost();

        var allowed = BuildMethod(27);
        var overLimit = BuildMethod(28);

        Assert.DoesNotContain(host.Analyze(allowed), diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong);
        Assert.Contains(host.Analyze(overLimit), diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong);
    }

    [Fact]
    public void Comments_and_blank_lines_do_not_count_but_attributes_and_braces_do()
    {
        using var host = new AnalyzerTestHost();
        var source = "// ignored\n\n[System.Obsolete]\n" + BuildClass(297);

        var diagnostics = host.Analyze(source);

        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Partial_type_is_counted_once_across_declarations()
    {
        using var host = new AnalyzerTestHost();

        var first = BuildPartialClass("PartA", 159);
        var second = BuildPartialClass("PartB", 159);

        var diagnostics = host.Analyze(first, second);

        Assert.Equal(1, diagnostics.Count(diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong));
    }

    [Fact]
    public void Interfaces_are_checked_by_type_rule()
    {
        using var host = new AnalyzerTestHost();
        var source = BuildInterface(299);

        Assert.Contains(host.Analyze(source), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Include_and_exclude_globs_control_analyzed_files()
    {
        using var host = new AnalyzerTestHost();
        host.WriteSettings("""
        {
          "schemaVersion": 1,
          "codeSize": {
            "typeMaxSloc": 10,
            "memberMaxSloc": 30,
            "includeGlobs": ["Assets/Included/**/*.cs"],
            "excludeGlobs": ["**/Generated/**"]
          }
        }
        """);

        var diagnostics = host.AnalyzeAt(
            new SourceFile("Assets/Included/Fixture.cs", BuildClass(10, "Included")),
            new SourceFile("Assets/Generated/Fixture.g.cs", BuildClass(10, "Generated")));

        Assert.Equal(1, diagnostics.Count(diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong));
    }

    [Fact]
    public void Baseline_allows_legacy_size_but_reports_growth()
    {
        using var host = new AnalyzerTestHost();
        var baseline = """
        {
          "schemaVersion": 1,
          "entries": [
            {
              "ruleId": "RYXPA1001",
              "assemblyName": "Assembly-CSharp",
              "symbolId": "T:C",
              "allowedSloc": 301
            }
          ]
        }
        """;
        host.WriteBaseline(baseline);

        Assert.DoesNotContain(host.Analyze(BuildClass(298)), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
        Assert.Contains(host.Analyze(BuildClass(299)), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Preprocessor_directives_count_as_code_lines()
    {
        using var host = new AnalyzerTestHost();
        var source = BuildClassWithDirectives(296);

        Assert.Contains(host.Analyze(source), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Inactive_preprocessor_branch_is_not_counted()
    {
        using var host = new AnalyzerTestHost();
        host.WriteSettings("""
        {
          "schemaVersion": 1,
          "codeSize": {
            "typeMaxSloc": 5,
            "memberMaxSloc": 30
          }
        }
        """);

        var source = "public class C\n{\n#if false\n" + BuildStatements(20, "private int ignored;") + "#endif\n}";

        Assert.DoesNotContain(host.Analyze(source), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Generated_files_are_ignored()
    {
        using var host = new AnalyzerTestHost();
        var source = "// <auto-generated />\n" + BuildClass(298);

        Assert.DoesNotContain(host.Analyze(source), diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Unity_editor_and_test_compilations_are_ignored()
    {
        using var host = new AnalyzerTestHost();
        var source = BuildClass(298);

        Assert.DoesNotContain(host.AnalyzeWithDefines(source, "UNITY_EDITOR"),
            diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
        Assert.DoesNotContain(host.AnalyzeWithDefines(source, "UNITY_INCLUDE_TESTS"),
            diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Long_constructor_and_operator_are_reported()
    {
        using var host = new AnalyzerTestHost();
        var source = """
        public class C
        {
            private int value;
            public C()
            {
        """ + BuildStatements(29) + """
            }
            public static C operator +(C left, C right)
            {
        """ + BuildStatements(28, "left.value++;") + """
                return left;
            }
        }
        """;

        var diagnostics = host.Analyze(source);

        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong && diagnostic.GetMessage().Contains("C()"));
        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong && diagnostic.GetMessage().Contains("operator"));
    }

    [Fact]
    public void Long_accessor_and_local_function_are_reported()
    {
        using var host = new AnalyzerTestHost();
        var source = """
        public class C
        {
            private int value;
            public int Value
            {
                get
                {
        """ + BuildStatements(28) + """
                    return value;
                }
            }

            public void Outer()
            {
                int Local(int input)
                {
        """ + BuildStatements(28, "input++;") + """
                    return input;
                }
                value = Local(value);
            }
        }
        """;

        var diagnostics = host.Analyze(source);

        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong && diagnostic.GetMessage().Contains("get"));
        Assert.True(diagnostics.Count(diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong) >= 2);
    }

    [Fact]
    public void Expression_bodied_property_is_reported()
    {
        using var host = new AnalyzerTestHost();
        var builder = new StringBuilder("public class C\n{\n    public int Value =>\n");
        for (var index = 0; index < 29; index++)
            builder.AppendLine("        0 +");
        builder.AppendLine("        0;\n}");

        Assert.Contains(host.Analyze(builder.ToString()), diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong);
    }

    [Fact]
    public void Long_destructor_conversion_and_indexer_are_reported()
    {
        using var host = new AnalyzerTestHost();
        var builder = new StringBuilder("public class C\n{\n    private int value;\n    ~C()\n    {\n");
        builder.Append(BuildStatements(29));
        builder.AppendLine("    }");
        builder.AppendLine("    public static explicit operator int(C other)");
        builder.AppendLine("    {");
        builder.Append(BuildStatements(29, "other.value++;"));
        builder.AppendLine("        return other.value;");
        builder.AppendLine("    }");
        builder.AppendLine("    public int this[int index] =>");
        for (var index = 0; index < 29; index++)
            builder.AppendLine("        0 +");
        builder.AppendLine("        0;");
        builder.AppendLine("}");

        var diagnostics = host.Analyze(builder.ToString());

        Assert.True(diagnostics.Count(diagnostic => diagnostic.Id == DiagnosticIds.MemberTooLong) >= 3);
    }

    [Fact]
    public void Invalid_settings_are_reported_without_size_diagnostics()
    {
        using var host = new AnalyzerTestHost();
        host.WriteSettings("{\"schemaVersion\":2,\"codeSize\":{\"typeMaxSloc\":300,\"memberMaxSloc\":30}}");

        var diagnostics = host.Analyze(BuildClass(298));

        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.InvalidSettings);
        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Invalid_baseline_is_reported_without_size_diagnostics()
    {
        using var host = new AnalyzerTestHost();
        host.WriteBaseline("{\"schemaVersion\":1,\"entries\":[{\"ruleId\":\"RYXPA1001\",\"assemblyName\":\"Assembly-CSharp\",\"symbolId\":\"T:C\",\"allowedSloc\":1},{\"ruleId\":\"RYXPA1001\",\"assemblyName\":\"Assembly-CSharp\",\"symbolId\":\"T:C\",\"allowedSloc\":2}]}");

        var diagnostics = host.Analyze(BuildClass(298));

        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.InvalidBaseline);
        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.TypeTooLong);
    }

    [Fact]
    public void Capture_uses_transportable_warning_diagnostics_for_heartbeat_and_records()
    {
        using var host = new AnalyzerTestHost();
        host.WriteSettings("{\"schemaVersion\":1,\"codeSize\":{\"typeMaxSloc\":1,\"memberMaxSloc\":1}}");
        host.WriteCapture("{\"nonce\":\"capture\",\"mode\":\"Initial\"}");

        var diagnostics = host.Analyze("public class C\n{\n    public void M()\n    {\n        int value = 1;\n    }\n}");

        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.CaptureHeartbeat);
        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == DiagnosticIds.CaptureRecord);
        Assert.All(diagnostics.Where(diagnostic =>
                diagnostic.Id == DiagnosticIds.CaptureHeartbeat || diagnostic.Id == DiagnosticIds.CaptureRecord),
            diagnostic => Assert.Equal(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning, diagnostic.Severity));
    }

    private static string BuildClass(int fieldLines, string name = "C")
    {
        var builder = new StringBuilder($"public class {name}\n{{\n");
        for (var index = 0; index < fieldLines; index++)
            builder.AppendLine($"    private int field{index};");
        builder.AppendLine("}");
        return builder.ToString();
    }


    private static string BuildPartialClass(string partName, int fieldLines)
    {
        var builder = new StringBuilder($"public partial class C\n{{\n");
        for (var index = 0; index < fieldLines; index++)
            builder.AppendLine($"    private int {partName}Field{index};");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildClassWithDirectives(int fieldLines)
    {
        var builder = new StringBuilder("public class C\n{\n#if true\n");
        for (var index = 0; index < fieldLines; index++)
            builder.AppendLine($"    private int field{index};");
        builder.AppendLine("#endif\n}");
        return builder.ToString();
    }

    private static string BuildStatements(int count, string statement = "value++;")
    {
        var builder = new StringBuilder();
        for (var index = 0; index < count; index++)
            builder.AppendLine("        " + statement);
        return builder.ToString();
    }

    private static string BuildInterface(int memberLines)
    {
        var builder = new StringBuilder("public interface C\n{\n");
        for (var index = 0; index < memberLines; index++)
            builder.AppendLine($"    void Method{index}();");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildMethod(int bodyLines)
    {
        var builder = new StringBuilder("public class C\n{\n    private int value;\n    public void M()\n    {\n");
        for (var index = 0; index < bodyLines; index++)
            builder.AppendLine("        value++;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
